package com.vecent.ssspeedtest.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vecent.ssspeedtest.dao.SSServer;
import com.vecent.ssspeedtest.model.bean.TotalSpeedTestResult;

import com.vecent.ssspeedtest.greendao.SSServerDao;
import com.vecent.ssspeedtest.greendao.TotalSpeedTestResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sSServerDaoConfig;
    private final DaoConfig totalSpeedTestResultDaoConfig;

    private final SSServerDao sSServerDao;
    private final TotalSpeedTestResultDao totalSpeedTestResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sSServerDaoConfig = daoConfigMap.get(SSServerDao.class).clone();
        sSServerDaoConfig.initIdentityScope(type);

        totalSpeedTestResultDaoConfig = daoConfigMap.get(TotalSpeedTestResultDao.class).clone();
        totalSpeedTestResultDaoConfig.initIdentityScope(type);

        sSServerDao = new SSServerDao(sSServerDaoConfig, this);
        totalSpeedTestResultDao = new TotalSpeedTestResultDao(totalSpeedTestResultDaoConfig, this);

        registerDao(SSServer.class, sSServerDao);
        registerDao(TotalSpeedTestResult.class, totalSpeedTestResultDao);
    }
    
    public void clear() {
        sSServerDaoConfig.clearIdentityScope();
        totalSpeedTestResultDaoConfig.clearIdentityScope();
    }

    public SSServerDao getSSServerDao() {
        return sSServerDao;
    }

    public TotalSpeedTestResultDao getTotalSpeedTestResultDao() {
        return totalSpeedTestResultDao;
    }

}
