language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
    - extra-android-support

before_script:
    - chmod a+x ./gradlew

script:
   - ./gradlew assembleRelease  