language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
    - extra-android-support

stages:
  - name: build
    if: branch = master

install:
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

jobs:
  include:
    stage: build
    script: 
      - chmod a+x ./gradlew && ./gradlew assembleRelease
      



