language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
    - extra-android-support

script:
  - echo $PWD  