language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
    - extra-android-support

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache


install:
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

jobs:
  include:
    stage: build
    script: 
      - chmod a+x ./gradlew && ./gradlew assembleRelease && ls app/build/outputs/apk/
    # depoly:
    #     provider: releases 
    #     user: $GITHUB_USERNAME
    #     password: $GITHUB_PASSWD
    #     file: app/build/outputs/apk/app-release.apk  
      



